---
-
 name: "Install Apache2"
 apt: name={{ item }} state=present
 with_items:
  - apache2
  - apache2-dev
 sudo: true

-
 name: "Templating default-ssl site"
 template: src=default-ssl.j2 dest=/etc/apache2/sites-available/default-ssl.conf owner=www-data group=www-data
 sudo: true
-
 name: "Templating default site"
 template: src=default.j2 dest=/etc/apache2/sites-available/000-default.conf owner=www-data group=www-data
 sudo: true

-
 name: "Enable ssl module"
 apache2_module: state=present name=ssl
 sudo: true

-
 name: "Enable default-ssl site"
 shell: a2ensite default-ssl
 sudo: true
 notify: restart apache2

-
 name: "Starting Apache2"
 service: name=apache2 state=started enabled=yes
 sudo: true

