- name: configure the cvl menues
  copy: src=cvl.menu dest=/etc/xdg/menus/applications-merged/cvl.menu mode=644 owner=root group=root
  sudo: true

- name: configure the cvl backgroud image 
  copy: src={{ item }} dest=/usr/share/backgrounds/i{{ item }} mode=644 owner=root group=root
  with_items:
    - cvl_desktop.svg
    - default.xml
  sudo: true


