---
  - name: restart munge
    service: name=munge state=restarted
    sudo: true

  - name: restart slurm
    service: name=slurm state=restarted
    sudo: true

  - name: restart slurmdbd
    service: name=slurmdbd state=restarted
    sudo: true

