---

- name: template secure script
  template: src=set_root_passwd_sql.j2 dest=/tmp/set_root_passwd.sql mode=600 owner=root
  sudo: true

- name: run script
  shell: cat /tmp/set_root_passwd.sql | mysql -u root
  sudo: true
  ignore_errors: true

- name: test passwd set
  shell: echo "show databases" | mysql -u root --password={{ sqlrootPasswd }}
