---
- name: "Check shibbolenth directory"
  file: dest=/etc/shibboleth state=directory mode=0655
  sudo: true
  when: shibbolenth_file is defined

- name: "Copying the shisbbolenth files"
  template: src="../../../files/{{ item }}" dest="/etc/shibboleth/{{ item }}" mode=0644
  sudo: true
  with_items:
    - "{{ shibbolenth_file.aaf }}"
    - "{{ shibbolenth_file.cert }}"
  when: shibbolenth_file is defined

- name: "Copying the apache key file"
  template: src="../../../files/{{ apache_key_file }}" dest="{{ x509_key_file }}" mode=0644
  sudo: true
  when: apache_key_file is defined

- name: "Copying the apache cert file"
  template: src="../../../files/{{ apache_cert_file }}" dest="{{ x509_cert_file }}" mode=0644
  sudo: true
  when: apache_cert_file is defined


